sausages_by_country ={
    'United Arab Emirates': 'Merguez',
    'Albania': 'Suxhuk',
    'Armenia': 'Basturma Makkara',
    'Angola': 'Chouriço Angolano',
    'Argentina': 'Chorizo Argentino',
    'Austria': 'Wiener Würstchen',
    'Australia': 'Kenguru Makkara',
    'Aruba': 'Aruban Papaya Makkara',
    'Azerbaijan': 'Lula Kebab Makkara',
    'Bangladesh': 'Naga Makkara',
    'Belgium': 'Boudin Blanc',
    'Bulgaria': 'Lukanka',
    'Bahrain': 'Lamb Kofta Makkara',
    'Brunei': 'Beef Rendang Makkara',
    'Bolivia': 'Salchicha Cochabambina',
    'Caribbean Netherlands': 'Karibian Mausteinen Makkara',
    'Brazil': 'Linguiça',
    'Bahamas': 'Conch Makkara',
    'Botswana': 'Boerewors',
    'Belarus': 'Krakowska',
    'Belize': 'Belizean Jerk Makkara',
    'Canada': 'Maple Bacon Makkara',
    'Congo (Kinshasa)': 'Congolese Beef Makkara',
    'Switzerland': 'Cervelat',
    'Cook Islands': 'Taro Leaf Makkara',
    'Chile': 'Longaniza',
    'China': 'Lap Cheong',
    'Colombia': 'Butifarra',
    'Costa Rica': 'Chorizo Tico',
    'Cuba': 'Salchicha Habanera',
    'Cape Verde': 'Linguiça Cabo Verde',
    'Curaçao': 'Keshi Yena Makkara',
    'Cyprus': 'Sheftalia',
    'Czech Republic': 'Jelito',
    'Germany': 'Bratwurst',
    'Djibouti': 'Spiced Camel Makkara',
    'Denmark': 'Medisterpølse',
    'Dominican Republic': 'Longaniza Dominicana',
    'Algeria': 'Merguez',
    'Ecuador': 'Chorizo Ecuatoriano',
    'Estonia': 'Verivorst',
    'Egypt': 'Mombar',
    'Spain': 'Chorizo',
    'Ethiopia': 'Tibs Makkara',
    'Finland': 'Makkara',
    'France': 'Andouille',
    'United Kingdom': 'Cumberland Makkara',
    'Georgia': 'Kupati',
    'French Guiana': 'Creole Makkara',
    'Ghana': 'Chinchinga Makkara',
    'Gambia': 'Yassa Makkara',
    'Guadeloupe': 'Boudin Créole',
    'Greece': 'Loukaniko',
    'Guatemala': 'Chorizo Guatemalteco',
    'Guam': 'Chamorro Red Makkara',
    'Hong Kong': 'Lap Cheong',
    'Croatia': 'Kulen',
    'Haiti': 'Sos Pwa Makkara',
    'Hungary': 'Kolbász',
    'Indonesia': 'Sate Lilit Makkara',
    'Ireland': 'Irish Breakfast Makkara',
    'Israel': 'Kebab Makkara',
    'India': 'Spicy Chicken Makkara',
    'Iraq': 'Kebab Makkara',
    'Iran': 'Sosis Bandari',
    'Iceland': 'Lamb Makkara',
    'Italy': 'Salami',
    'Jamaica': 'Jerk Makkara',
    'Jordan': 'Mansaf Lamb Makkara',
    'Japan': 'Arabiki Makkara',
    'Kenya': 'Nyama Choma Makkara',
    'Kyrgyzstan': 'Kazy Makkara',
    'Cambodia': 'Twak Makkara',
    'South Korea': 'Soondae',
    'Kuwait': 'Kebab Makkara',
    'Cayman Islands': 'Jerk Makkara',
    'Kazakhstan': 'Kazy',
    'Lebanon': 'Makanek',
    'Saint Lucia': 'Green Fig Makkara',
    'Sri Lanka': 'Spicy Chicken Makkara',
    'Liberia': 'Pepper Makkara',
    'Lithuania': 'Skilandis',
    'Luxembourg': 'Thüringer',
    'Latvia': 'Speķa Pīrāgi Makkara',
    'Libya': 'Spicy Lamb Makkara',
    'Morocco': 'Merguez',
    'Montenegro': 'Njeguška kobasica',
    'Madagascar': 'Zebu Makkara',
    'North Macedonia': 'Kulen',
    'Mali': 'Bambara Makkara',
    'Burma': 'Shan Makkara',
    'Mongolia': 'Khuushuur Makkara',
    'Macau': 'Portuguese Linguiça',
    'Martinique': 'Boudin Antillais',
    'Mauritania': 'Spiced Camel Makkara',
    'Malta': 'Maltese Makkara',
    'Mauritius': 'Rougaille Makkara',
    'Maldives': 'Fish Makkara',
    'Mexico': 'Chorizo',
    'Malaysia': 'Chicken Satay Makkara',
    'Mozambique': 'Peri-Peri Makkara',
    'Namibia': 'Boerewors',
    'New Caledonia': 'Venison Makkara',
    'Niger': 'Millet Makkara',
    'Nigeria': 'Suya Makkara',
    'Netherlands': 'Rookworst',
    'Norway': 'Kjøttpølse',
    'Nepal': 'Yak Makkara',
    'New Zealand': 'Venison Makkara',
    'Oman': 'Shuwa Makkara',
    'Panama': 'Chorizo Panameño',
    'Perú': 'Salchicha Huachana',
    'French Polynesia': 'Tahitian Coconut Makkara',
    'Papua New Guinea': 'Crocodile Makkara',
    'Philippines': 'Longganisa',
    'Pakistan': 'Seekh Kebab Makkara',
    'Poland': 'Kielbasa',
    'Puerto Rico': 'Salchichón',
    'Portugal': 'Linguiça',
    'Qatar': 'Kebab Makkara',
}
duplicates = []
gone_through = []

for makkara in sausages_by_country.values():
    if makkara in gone_through:
        duplicates.append(makkara)
    gone_through.append(makkara)

print(sorted(duplicates))
print(len(sausages_by_country))
#'Réunion': 'Roug &#8203;:contentReference[oaicite:0]{index=0}&#8203;