makkaras_dictionary = {
    "United Arab Emirates": "Merguez Makkara",
    "Albania": "Suxhuk Makkara",
    "Armenia": "Basturma Makkara",
    "Angola": "Linguiça Angolana",
    "Argentina": "Chorizo Argentino",
    "Austria": "Wiener Makkara",
    "Australia": "Aussie BBQ Makkara",
    "Aruba": "Aruban Tropical Makkara",
    "Azerbaijan": "Kovurma Makkara",
    "Bangladesh": "Bangladeshi Spiced Makkara",
    "Belgium": "Boudin Blanc Makkara",
    "Bulgaria": "Lukanka Makkara",
    "Bahrain": "Bahraini Lamb Makkara",
    "Brunei": "Bruneian Chicken Makkara",
    "Bolivia": "Saltena Makkara",
    "Caribbean Netherlands": "Netherlands Antilles Makkara",
    "Brazil": "Linguica Makkara",
    "Bahamas": "Bahamian Seafood Makkara",
    "Botswana": "Botswanan Beef Makkara",
    "Belarus": "Belorusskaya Kolbasa Makkara",
    "Belize": "Belizean Citrus Makkara",
    "Canada": "Maple Makkara",
    "Congo (Kinshasa)": "Congolese Smoked Makkara",
    "Switzerland": "Cervelat Makkara",
    "Cook Islands": "Cook Islands Pineapple Makkara",
    "Chile": "Longaniza Chilena Makkara",
    "China": "Lap Cheong Makkara",
    "Colombia": "Butifarra Makkara",
    "Costa Rica": "Chorizo Tico Makkara",
    "Cuba": "Cuban Mojo Makkara",
    "Cape Verde": "Cachupa Makkara",
    "Curaçao": "Curacao Spicy Makkara",
    "Cyprus": "Sheftalia Makkara",
    "Czech Republic": "Jelito Makkara",
    "Germany": "Bratwurst Makkara",
    "Djibouti": "Djiboutian Goat Makkara",
    "Denmark": "Polser Makkara",
    "Dominican Republic": "Dominican Rum Makkara",
    "Algeria": "Merguez Makkara",
    "Ecuador": "Chorizo Ecuatoriano Makkara",
    "Estonia": "Estonian Blood Makkara",
    "Egypt": "Egyptian Spiced Makkara",
    "Spain": "Chorizo Makkara",
    "Ethiopia": "Ethiopian Beef Makkara",
    "Finland": "HKSininen Makkara",
    "France": "Andouille Makkara",
    "United Kingdom": "Cumberland Makkara",
    "Georgia": "Kupati Makkara",
    "French Guiana": "French Guiana Herb Makkara",
    "Ghana": "Ghanaian Spiced Makkara",
    "Gambia": "Gambian Peanut Makkara",
    "Guadeloupe": "Guadeloupe Tropical Makkara",
    "Greece": "Loukaniko Makkara",
    "Guatemala": "Guatemalan Chorizo Makkara",
    "Guam": "Guam BBQ Makkara",
    "Hong Kong": "Hong Kong Pork Makkara",
    "Croatia": "Kulen Makkara",
    "Haiti": "Haitian Creole Makkara",
    "Hungary": "Gyulai Kolbasz Makkara",
    "Indonesia": "Indonesian Satay Makkara",
    "Ireland": "White Pudding Makkara",
    "Israel": "Israeli Lamb Makkara",
    "India": "Goan Chorizo Makkara",
    "Iraq": "Iraqi Spiced Makkara",
    "Iran": "Iranian Saffron Makkara",
    "Iceland": "Icelandic Lamb Makkara",
    "Italy": "Salsiccia Makkara",
    "Jamaica": "Jamaican Jerk Makkara",
    "Jordan": "Jordanian Mint Makkara",
    "Japan": "Japanese Teriyaki Makkara",
    "Kenya": "Kenyan BBQ Makkara",
    "Kyrgyzstan": "Kazy Makkara",
    "Cambodia": "Cambodian Lemongrass Makkara",
    "South Korea": "Sundae Makkara",
    "Kuwait": "Kuwaiti Spice Makkara",
    "Cayman Islands": "Cayman Grilled Makkara",
    "Kazakhstan": "Kazy Makkara",
    "Lebanon": "Makanek Makkara",
    "Saint Lucia": "Saint Lucian Coconut Makkara",
    "Sri Lanka": "Sri Lankan Curry Makkara",
    "Liberia": "Liberian Makkara",
    "Lithuania": "Skilandis Makkara",
    "Luxembourg": "Luxembourg Herb Makkara",
    "Latvia": "Latvian Dill Makkara",
    "Libya": "Libyan Spiced Makkara",
    "Morocco": "Merguez Makkara",
    "Montenegro": "Njeguski Pršut Makkara",
    "Madagascar": "Madagascan Vanilla Makkara",
    "North Macedonia": "Macedonian Pepper Makkara",
    "Mali": "Malian Makkara",
    "Burma": "Burmese Lemongrass Makkara",
    "Mongolia": "Mongolian Yak Makkara",
    "Macau": "Macanese Pork Makkara",
    "Martinique": "Martinique Rum Makkara",
    "Mauritania": "Mauritanian Camel Makkara",
    "Malta": "Maltese Pork Makkara",
    "Mauritius": "Mauritian Seafood Makkara",
    "Maldives": "Maldivian Fish Makkara",
    "Mexico": "Chorizo Makkara",
    "Malaysia": "Malaysian Satay Makkara",
    "Mozambique": "Mozambican Peri-Peri Makkara",
    "Namibia": "Namibian Game Makkara",
    "New Caledonia": "New Caledonian Coconut Makkara",
    "Niger": "Nigerian Millet Makkara",
    "Nigeria": "Suya Makkara",
    "Netherlands": "Rookworst Makkara",
    "Norway": "Polse Makkara",
    "Nepal": "Nepalese Spiced Makkara",
    "New Zealand": "Kiwi BBQ Makkara",
    "Oman": "Omani Spiced Makkara",
    "Panama": "Panamanian Jerk Makkara",
    "Perú": "Chorizo Peruano Makkara",
    "French Polynesia": "Polynesian Tropical Makkara",
    "Papua New Guinea": "Papuan Makkara",
    "Philippines": "Longganisa Makkara",
    "Pakistan": "Pakistani Makkara",
    "Poland": "Kielbasa Makkara",
    "Puerto Rico": "Puerto Rican Makkara",
    "Portugal": "Linguica Makkara",
    "Qatar": "Qatari Spiced Makkara",
    "Réunion": "Reunion Creole Makkara",
    "Romania": "Carnati Makkara",
    "Serbia": "Sremska Makkara",
    "Russia": "Krakowska Makkara",
    "Rwanda": "Rwandan Makkara",
    "Saudi Arabia": "Saudi Lamb Makkara",
    "Solomon Islands": "Solomon Fish Makkara",
    "Seychelles": "Seychelles Seafood Makkara",
    "Sudan": "Sudanese Spiced Makkara",
    "Sweden": "Isterband Makkara",
    "Singapore": "Singaporean Satay Makkara",
    "Slovenia": "Kranjska Klobasa Makkara",
    "Slovakia": "Slovakian Garlic Makkara",
    "Sierra Leone": "Sierra Leone Peanut Makkara",
    "Senegal": "Senegalese Spicy Makkara",
    "Suriname": "Suriname Tropical Makkara",
    "South Sudan": "South Sudan Spiced Makkara",
    "El Salvador": "Salvadoran Makkara",
    "Sint Maarten": "Sint Maarten BBQ Makkara",
    "Syria": "Syrian Spiced Makkara",
    "Eswatini": "Swazi Makkara",
    "Turks and Caicos Islands": "Turks and Caicos Spiced Makkara",
    "Chad": "Chadian Makkara",
    "Thailand": "Thailand Makkara",
    "Turkmenistan": "Turkmenistan Makkara",
    "Tunisia": "Tunisia Makkara",
    "Turkey": "Kebab Makkara",
    "Taiwan": "Taiwan Makkara",
    "Tanzania": "Tanzania Makkara",
    "Ukraine": "Ukraine Makkara",
    "Uganda": "Ugand Makkara",
    "United states": "United States Makkara",
    "Uruguay": "Uruguay Makkara",
    "Uzbekistan": "Uzbekistan Makkara",
    "Venezuela": "Venezuela Makkara",
    "Vietnam": "Vietnam Makkara",
    "Vanautu": "Vanautu Makkara",
    "South Africa": "WakaWakaMakkara",
    "Zambia": "Zambia Makkara",
    "Zimbabwe": "Zimbabwe Makkara",
}

score_value_makkara = [42000, 25620, 37380, 7560, 31920, 20580, 1260, 34860, 19740, 19740, 5460, 21420, 7140, 1260, 15960,
                 5880, 19740, 26040, 16380, 33180, 16380, 3780, 27720, 22680, 35280, 840, 18900, 3780, 31500, 41580,
                 26880, 38220, 20580, 35700, 28140, 35280, 33180, 34440, 25620, 31500, 19320, 15960, 40740, 28560,
                 21000, 17640, 24360, 27300, 27300, 12180, 17640, 8400, 4200, 3780, 15960, 38220, 26040, 26460, 8400,
                 38640, 20160, 40740, 7560, 31080, 36540, 42069, 9660, 9660, 13020, 36120, 18480, 17640, 34860, 14700,
                 7140, 29820, 7560, 41580, 32760, 41160, 36960, 18900, 3360, 24780, 5880, 34860, 21840, 32760, 29400,
                 10080, 23940, 8820, 8400, 13860, 13020, 16800, 12180, 36120, 5880, 5880, 27720, 29820, 40740, 26040,
                 36960, 12600, 6300, 1260, 20580, 25200, 7140, 6300, 33600, 35280, 27720, 3780, 39060, 2940, 28980,
                 15120, 42000, 31080, 17220, 2520, 11340, 33600, 8400, 5040, 34440, 2520, 13440, 21420, 4620, 13440,
                 34440, 34860, 37380, 26880, 3780, 10080, 24360, 40740, 30660, 3360, 2100, 26880, 26880, 21000, 29400,
                 24360, 25620, 10080, 10080, 14280, 37800, 29820, 4200, 25620, 36540, 28560]


iso_country_list = [
    "AE", "AL", "AM", "AO", "AR", "AT", "AU", "AW", "AZ", "BD", "BE", "BG", "BH", "BN", "BO", "BQ",
    "BR", "BS", "BW", "BY", "BZ", "CA", "CD", "CH", "CK", "CL", "CN", "CO", "CR", "CU", "CV", "CW",
    "CY", "CZ", "DE", "DJ", "DK", "DO", "DZ", "EC", "EE", "EG", "ES", "ET", "FI", "FR", "GB", "GE",
    "GF", "GH", "GM", "GP", "GR", "GT", "GU", "HK", "HR", "HT", "HU", "ID", "IE", "IL", "IN", "IQ",
    "IR", "IS", "IT", "JM", "JO", "JP", "KE", "KG", "KH", "KR", "KW", "KY", "KZ", "LB", "LC", "LK",
    "LR", "LT", "LU", "LV", "LY", "MA", "ME", "MG", "MK", "ML", "MM", "MN", "MO", "MQ", "MR", "MT",
    "MU", "MV", "MX", "MY", "MZ", "NA", "NC", "NE", "NG", "NL", "NO", "NP", "NZ", "OM", "PA", "PE",
    "PF", "PG", "PH", "PK", "PL", "PR", "PT", "QA", "RE", "RO", "RS", "RU", "RW", "SA", "SB", "SC",
    "SD", "SE", "SG", "SI", "SK", "SL", "SN", "SR", "SS", "SV", "SX", "SY", "SZ", "TC", "TD", "TH",
    "TM", "TN", "TR", "TW", "TZ", "UA", "UG", "US", "UY", "UZ", "VE", "VN", "VU", "ZA", "ZM", "ZW"
]